-- MySQL Script generated by MySQL Workbench
-- 11/19/14 11:09:04
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema PersoLib
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema PersoLib
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `PersoLib` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `PersoLib` ;

-- -----------------------------------------------------
-- Table `PersoLib`.`USR_Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PersoLib`.`USR_Usuario` (
  `USR_id` INT NOT NULL AUTO_INCREMENT,
  `USR_email` VARCHAR(45) NOT NULL,
  `USR_nome` VARCHAR(45) NOT NULL,
  `USR_senha` VARCHAR(45) NOT NULL,
  `USR_ativo` TINYINT(1) NOT NULL,
  PRIMARY KEY (`USR_id`),
  UNIQUE INDEX `USR_id_UNIQUE` (`USR_id` ASC),
  UNIQUE INDEX `USR_email_UNIQUE` (`USR_email` ASC))
ENGINE = InnoDB;



SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
